# Generated by Django 4.2.5 on 2023-09-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager',
            new_name='report_to',
        ),
    ]
